{% set name = "pyspnego" %}
{% set version = "0.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 994388d308fb06e4498365ce78d222bf4f3570b6df4ec95738431f61510c971b

build:
  number: 0
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pyspnego-parse = spnego.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cryptography
    - sspilib >=0.1.0  # [win]
    # Optional dependency for pyspengo-parse, see https://github.com/jborean93/pyspnego#optional-requirements
    - ruamel.yaml
  run_constrained:
    - python-gssapi >=1.6.0  # [not win]
    - pykrb5 >=0.3.0         # [not win]


# Windows fails those tests
{% set tests_to_skip = "test_negotiate_through_python_ntlm" %}
{% set tests_to_skip = tests_to_skip + " or test_negotiate_with_ntlm_hash" %}
{% set tests_to_skip = tests_to_skip + " or test_sspi_ntlm_auth_no_sign_or_seal" %}
{% set tests_to_skip = tests_to_skip + " or test_sspi_ntlm_auth" %}
{% set tests_to_skip = tests_to_skip + " or test_sspi_ntlm_lm_compat" %}
{% set tests_to_skip = tests_to_skip + " or test_credssp_multiple_creds" %}
{% set tests_to_skip = tests_to_skip + " or test_ntlm_iov_wrapping" %}
{% set tests_to_skip = tests_to_skip + " or test_ntlm_iov_unwrapping_as_stream" %}
{% set tests_to_skip = tests_to_skip + " or test_sspi_wrap_no_encryption" %}

test:
  source_files:
    - tests
  imports:
    - spnego
    - spnego._ntlm_raw
  requires:
    - pip
    - pytest
    - pytest-mock
    - sspilib >=0.1.0  # [win]
  commands:
    - pip check
    - pytest tests -v  # [not win]
    - pytest tests -v -k "not ({{ tests_to_skip }})"  # [win]

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jborean93/pyspnego
  doc_url: https://github.com/jborean93/pyspnego/blob/main/README.md
  description: |
    Library to handle SPNEGO (Negotiate, NTLM, Kerberos) and CredSSP authentication.
    Also includes a packet parser that can be used to decode
    raw NTLM/SPNEGO/Kerberos tokens into a human readable format.

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
