{% set name = "pyspnego" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e16cb331f1bd9c85f9b80e2be04bb5da2ecaff678cc0342f68b45e4667d7966

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pyspnego-parse = spnego.__main__:main

requirements:
  build:                       # [win]
    - {{ compiler('c') }}      # [win]
  host:
    - python
    - cython >=0.29.29,<3.0.0  # [win]
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cryptography
    # Optional dependency for pyspengo-parse, see https://github.com/jborean93/pyspnego#optional-requirements
    - ruamel.yaml
  run_constrained:
    - python-gssapi >=1.6.0  # [not win]
    - pykrb5 >=0.3.0         # [not win]

test:
  source_files:
    - tests
  imports:
    - spnego
    - spnego._ntlm_raw
    - spnego._sspi_raw  # [win]
  requires:
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jborean93/pyspnego
  doc_url: https://github.com/jborean93/pyspnego/blob/main/README.md
  description: |
    Library to handle SPNEGO (Negotiate, NTLM, Kerberos) and CredSSP authentication.
    Also includes a packet parser that can be used to decode
    raw NTLM/SPNEGO/Kerberos tokens into a human readable format.

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
