{% set name = "pyspnego" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspnego-{{ version }}.tar.gz
  sha256: e0499cc066c56762f8a315bb053243d34240cb85e384afc6b87b4fa0142543df

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv  # [not win]
  entry_points:
    - pyspnego-parse = spnego.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cryptography 39.0.1
    - cython 0.29.32
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cryptography
    # Optional dependency, see https://github.com/jborean93/pyspnego#optional-requirements
    # This package isn't included in SOW Packages list on s390x, 
    # and ruamel.yaml isn't available on s390x
    - ruamel.yaml  # [not s390x]
  # While pyspnego supports Kerberos authentication on Linux, 
  # it isn't included by default due to its reliance on system packages to be present.
  # For Kerberos authentication on Linux python-gssapi and pykrb5 can be installed 
  # to add extra features that do not come with the base package
  #run_constrained:
  #  - python-gssapi >=1.5.0  # [not win]

test:
  imports:
    - spnego
    - spnego._ntlm_raw
    - spnego._sspi_raw  # [win]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/jborean93/pyspnego/blob/main/LICENSE
  dev_url: https://github.com/jborean93/pyspnego
  doc_url: https://github.com/jborean93/pyspnego/blob/main/README.md
  description: |
    Library to handle SPNEGO (Negotiate, NTLM, Kerberos) and CredSSP authentication. 
    Also includes a packet parser that can be used to decode raw NTLM/SPNEGO/Kerberos tokens into a human readable format.

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
