{% set name = "pyspnego" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a22c23aeae7b4424fdb2482450d3f8302ac012e2644e1cfe735cf468fcd12ed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pyspnego-parse = spnego.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cryptography
    - sspilib >= 0.1.0       # [win]
    # Optional dependency, see https://github.com/jborean93/pyspnego#optional-requirements
    # This package isn't available on s390x,
    # and ruamel.yaml isn't available on s390x
    - ruamel.yaml            # [not s390x]
  run_constrained:
    - python-gssapi >=1.6.0  # [not win]
    - pykrb5 >=0.3.0         # [not win]

test:
  imports:
    - spnego
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jborean93/pyspnego
  doc_url: https://github.com/jborean93/pyspnego/blob/main/README.md
  description: |
    Library to handle SPNEGO (Negotiate, NTLM, Kerberos) and CredSSP authentication. 
    Also includes a packet parser that can be used to decode raw NTLM/SPNEGO/Kerberos tokens into a human readable format.

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
