{% set name = "pyspnego" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspnego-{{ version }}.tar.gz
  sha256: a2963d52b64ecd7df3f8e9a311a423e75bd4bcc5944d46da16837607f9f6e667

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cryptography
    - cython
    - pip
  run:
    - python
    - cryptography
    - ruamel.yaml
  run_constrained:
    - python-gssapi >=1.5.0  # [not win]

test:
  imports:
    - spnego
    - spnego._ntlm_raw
    - spnego._sspi_raw  # [win]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
